### ISSUE TITLE
Rebuilding the app throws this error

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1590]
```
04-28 20:29:34.431    4462-4462/mozilla.org.webmaker E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: mozilla.org.webmaker, PID: 4462
    java.lang.RuntimeException: Unable to instantiate application mozilla.org.webmaker.WebmakerApplication: java.lang.IllegalStateException: Unable to get package info for mozilla.org.webmaker; is package not installed?
            at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalStateException: Unable to get package info for mozilla.org.webmaker; is package not installed?
            at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:409)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:555)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by thisandagain** [comment]
I occasionally hit this as well. I often notice it when switching between simulator and device. Does running an `adb kill-server` and `killall adb` help at all?

**Comment by ryanw-ny** [comment]
I've encountered this issue before, I'll put it on my list to work on tomorrow. :smile:

**Comment by thisandagain** [comment]
:boom: Thanks @ryanw-ny !

**Comment by ryanw-ny** [comment]
The reason this is occurring is because the Android Virtual Device manager, has a very small amount of memory on it on the main GUI thread. Which is essentially where everything we are doing is being performed, so we have two solutions. Either add a multi-threading solution which will fix the problem, or encourage people using the virtual emulator to increase their RAM sizes appropriately.

What do you guys think? /cc @thisandagain @k88hudson

**Comment by k88hudson** [comment]
@ryanw-ny hm, that could definitely be an issue. In my case, I'm not using an emulator at all, so it would definitely have to be something else

Also, weirdly, this has stopped happening to me since last night.. :sheep:

**Comment by ryanw-ny** [comment]
@k88hudson Yeah definitely in that case, something wacky is going on. Have you tried other devices? Anything that might have caused it to stop happening? I'll put this on hold until it starts occurring again, it might have been a small quirk or something of that sort.

**Comment by thisandagain** [comment]
Closer due to lack of activity. Please re-open if it comes back up.

**Comment by AkshayRaj** [comment]
This happened to me on Nexus6. App was working fine. Made some changes and got a succesful build. But this happens.

06-18 13:20:10.645  31218-31218/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.apiosystems.transdevapp.debug, PID: 31218
    java.lang.RuntimeException: Unable to instantiate application com.apiosystems.transdevapp.ApioApplication: java.lang.IllegalStateException: Unable to get package info for com.apiosystems.transdevapp.debug; is package not installed?
            at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalStateException: Unable to get package info for com.apiosystems.transdevapp.debug; is package not installed?
            at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:409)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:555)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
06-18 13:20:10.682     812-1292/? I/ActivityManager﹕ Activity reported stop, but no longer stopping: ActivityRecord{235641cb u0 com.metago.astro/.MainActivity t76}
06-18 13:20:10.689  28142-28142/? E/ActivityThread﹕ Performing stop of activity that is not resumed: {com.metago.astro/com.metago.astro.MainActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.metago.astro/com.metago.astro.MainActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.access$1100(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
